server:
  port: 9080
  servlet:
    context-path: /customers/v1
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health, info, hystrix.stream  
spring:
  datasource:
    url: jdbc:mysql://bootcamp.ckyzngvmlkpk.sa-east-1.rds.amazonaws.com:3306/celula2
    username: celula2
    password: Celula02!!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

